# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5f3ea05240515e370f95b5c122a0ec2b590372f051d98d190d93806be450776edf1e451e202187c6fa0ca6c6f23d6c7e04737f645b29ff63a03249a5fdf39cc5

test:
  secret_key_base: 252b80a1b9f661c5dc0dabccdc41e1584ea4bd7729e8b360ac1b6fa6be6225f730dbe5f2b3042e760b133e9d2596e83aa97f112ab239114f2c9efae0cff83e30

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
